FROM node:12 as build-env

WORKDIR /app

COPY packages packages
COPY projects/front/web projects/front/web
COPY projects/back/graphql projects/back/graphql

COPY package.json package.json
COPY lerna.json lerna.json
COPY .eslintrc .eslintrc
COPY .prettierrc .prettierrc
COPY tsconfig.json tsconfig.json
COPY package-lock.json package-lock.json

RUN yarn install
RUN yarn build:front-web

FROM nginx

FROM nginx:1.13.7

COPY nginx/default.conf /etc/nginx/sites-enabled/default
COPY nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=build-env /app/projects/front/web/dist /var/www

CMD ["nginx", "-g", "daemon off;"]
