export enum AuthModalState {
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  RESET_PASSWORD_STEP_2 = 'RESET_PASSWORD_STEP_2',
}

export const AUTH_MODAL_URL_KEY = 'loginModalState'
