export default {
  aboutUs: '/about-us',
  profitablePicksPage: '/profitable-picks',
  predictions: '/predictions',
  studio: '/studio',
  patreonAuth: '/patreonAuth',
  vipPicks: '/vip-picks',
  valuePicks: '/value-picks',
  botVsBookmaker: '/bot-vs-bookmaker',
  githubStudio: 'https://github.com/gepick/gepick-developer-studio',
  facebook: 'https://www.facebook.com/gefalkopick/',
  medium: 'https://medium.com/@edgaraskarka',
  patreon: 'https://www.patreon.com/user?u=18890621',
  signUpModal: '?signUpModal',
  subscriptionModal: '/vip-picks/?subscriptionModal',
  botExplorer: '/bot-explorer',
  botExplorerIntervalPage: '/bot-explorer-interval',
  bookmakerExplorer: '/bookmaker-explorer',
  bookmakerExplorerIntervalReportPage: '/bookmaker-explorer-interval-report',
  sureBetsPage: '/sure-bets',
  picksExplorerPage: '/picks-explorer',
  cryptoBotPage: '/crypto-bot',
  cryptoStrategyBackTestPage: '/crypto-strategy-back-test',
  cryptoTradeListPage: '/crypto-trade-list',
}
